import CheckedIcon from "@/assets/icons/checked-icon.svg?react";
import UncheckedIcon from "@/assets/icons/unchecked-icon.svg?react";
import NomadRemLogo from "@/assets/black-logo.svg?react";
import DatePicker from "@/components/shared/DatePicker";
import Loader from "@/components/shared/Loader";
import PhoneInput from "@/components/shared/PhoneInput";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import SearchableSelect from "@/components/ui/searchable-select";
import {
  useCitiesByCountry,
  useCountries,
  useStatesByCountry,
} from "@/hooks/data/useAddress";
import {
  useSubmitCustomerForm,
  useValidateCustomerFormToken,
} from "@/hooks/data/useCustomerForm";
import { cn } from "@/lib/utils";
import type { Country } from "@/services/address";
import { zodResolver } from "@hookform/resolvers/zod";
import { format } from "date-fns";
import React, { useState } from "react";
import { useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { useParams } from "react-router-dom";
import { z } from "zod";

// Simple authentication check
const isAuthenticated = () => {
  return !!localStorage.getItem("token");
};

// Form validation schema
const customerFormSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("Please enter a valid email address"),
  dateOfBirth: z.string().min(1, "Date of birth is required"),
  streetName: z.string().min(1, "Street name is required"),
  houseNumber: z.string().min(1, "House number is required"),
  postalCode: z.string().optional(),
  extraAddressDetails: z.string().optional(),
  cityId: z.number().min(1, "City is required"),
  stateId: z.number().optional(),
  countryId: z.number().min(1, "Country is required"),
  gender: z.enum(["male", "female", "other"], {
    required_error: "Gender is required",
  }),
  countryPhoneCode: z.string().min(1, "Country code is required"),
  phoneNumber: z.string().min(1, "Phone number is required"),
});

type CustomerFormData = z.infer<typeof customerFormSchema>;

interface CustomerFormProps {
  token?: string;
  mode?: "dialog" | "fullpage" | "preview";
  onClose?: () => void;
}

const CustomerForm: React.FC<CustomerFormProps> = ({
  token,
  mode = "fullpage",
  onClose,
}) => {
  const { token: urlToken } = useParams<{ token: string }>();
  // const navigate = useNavigate();
  const [t] = useTranslation("global");
  const effectiveToken = token || urlToken;
  const isUserAuthenticated = isAuthenticated();
  const isPreviewMode = mode === "preview";

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [submitError, setSubmitError] = useState<string>("");
  const [selectedGender, setSelectedGender] = useState<string>("male");

  // Validate token
  const {
    data: tokenValidation,
    isLoading: isValidating,
    error: validationError,
  } = useValidateCustomerFormToken(effectiveToken || "");

  // Fetch address data
  const { data: countries = [] } = useCountries();
  const [selectedCountryId, setSelectedCountryId] = useState<number | null>(
    null
  );
  const { data: cities = [] } = useCitiesByCountry(selectedCountryId);
  const { data: states = [] } = useStatesByCountry(selectedCountryId);

  // Submit mutation
  const submitMutation = useSubmitCustomerForm(effectiveToken || "");

  // NomadRem branding component
  const brandingSection = (
    <div className="text-center bg-gray-50 border border-gray-200 p-4 flex items-center justify-center">
      <div className="flex justify-center mb-2">
        <NomadRemLogo className="h-6" />
      </div>
      <p className="text-sm text-gray-500">
        This link to join NomadRem as a customer was generated by NomadRem
      </p>
    </div>
  );

  const form = useForm<CustomerFormData>({
    resolver: zodResolver(customerFormSchema),
    defaultValues: {
      firstName: "",
      lastName: "",
      email: "",
      dateOfBirth: "",
      streetName: "",
      houseNumber: "",
      postalCode: "",
      extraAddressDetails: "",
      cityId: 0,
      stateId: undefined,
      countryId: 0,
      gender: "male",
      countryPhoneCode: "",
      phoneNumber: "",
    },
  });

  // Handle country change
  const handleCountryChange = (countryId: number) => {
    setSelectedCountryId(countryId);
    form.setValue("countryId", countryId);
    form.setValue("cityId", 0);
    form.setValue("stateId", undefined);
  };

  // Country phone code options
  const countryPhoneOptions = countries.map((country: Country) => ({
    value: country.phone_code,
    label: country.name,
    code: country.phone_code,
    countryCode: country.iso2,
  }));

  const handleSubmit = async (data: CustomerFormData) => {
    // Don't submit if it's preview mode
    if (isPreviewMode) {
      return;
    }

    setIsSubmitting(true);
    setSubmitError("");

    try {
      const submissionData = {
        first_name: data.firstName,
        last_name: data.lastName,
        email: data.email,
        date_of_birth: data.dateOfBirth,
        street_name: data.streetName,
        house_number: data.houseNumber,
        postal_code: data.postalCode || "", // Provide default empty string for optional postal code
        extra_address_details: data.extraAddressDetails || "",
        city_id: data.cityId,
        state_id: data.stateId || undefined, // Provide default undefined for optional state
        country_id: data.countryId,
        gender: data.gender,
        country_phone_code: data.countryPhoneCode,
        phone_number: data.phoneNumber,
        status: "active" as const,
      };

      await submitMutation.mutateAsync(submissionData);
      setSubmitSuccess(true);

      // Close dialog after success if in dialog mode
      if (mode === "dialog" && onClose) {
        setTimeout(() => {
          onClose();
        }, 2000);
      }
    } catch (error) {
      if (error instanceof Error) {
        setSubmitError(error.message);
      } else {
        setSubmitError("An unexpected error occurred. Please try again.");
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  // Loading state
  if (isValidating) {
    return (
      <div className="space-y-6">
        {brandingSection}
        <div className="flex justify-center items-center h-64">
          <Loader />
        </div>
      </div>
    );
  }

  // Error state - invalid, expired, or used token
  if (validationError || !tokenValidation?.id) {
    return (
      <div className="space-y-6">
        {brandingSection}
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <h2 className="text-2xl font-bold text-red-600 mb-4">
            {t("modules.pages.customerForm.linkExpired.title")}
          </h2>
          <p className="text-gray-600">
            {t("modules.pages.customerForm.linkExpired.message")}
          </p>
          {/* {mode === "fullpage" && (
            <Button
              onClick={() => navigate("/")}
              className="mt-4"
              variant="outline"
            >
              {t("modules.pages.customerForm.actions.goHome")}
            </Button>
          )} */}
          {isPreviewMode && (
            <Button onClick={onClose} className="mt-4" variant="outline">
              {t("modules.pages.customerForm.closePreview")}
            </Button>
          )}
        </div>
      </div>
    );
  }

  // Check if the form link is already used (successful_registration)
  if (tokenValidation?.status === "successful_registration") {
    return (
      <div className="space-y-6">
        {brandingSection}
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <h2 className="text-2xl font-bold text-orange-600 mb-4">
            {t("modules.pages.customerForm.linkUsed.title")}
          </h2>
          <p className="text-gray-600">
            {t("modules.pages.customerForm.linkUsed.message")}
          </p>
          {/* {mode === "fullpage" && (
            <Button
              onClick={() => navigate("/")}
              className="mt-4"
              variant="outline"
            >
              {t("common.actions.goHome")}
            </Button>
          )} */}
          {isPreviewMode && (
            <Button onClick={onClose} className="mt-4" variant="outline">
              {t("modules.pages.customerForm.closePreview")}
            </Button>
          )}
        </div>
      </div>
    );
  }

  // Check if the form link is expired
  if (tokenValidation?.status === "expired_link") {
    return (
      <div className="space-y-6">
        {brandingSection}
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <h2 className="text-2xl font-bold text-red-600 mb-4">
            {t("modules.pages.customerForm.linkExpired.title")}
          </h2>
          <p className="text-gray-600">
            {t("modules.pages.customerForm.linkExpired.message")}
          </p>
          {/* {mode === "fullpage" && (
            <Button
              onClick={() => navigate("/")}
              className="mt-4"
              variant="outline"
            >
              {t("common.actions.goHome")}
            </Button>
          )} */}
          {isPreviewMode && (
            <Button onClick={onClose} className="mt-4" variant="outline">
              {t("modules.pages.customerForm.closePreview")}
            </Button>
          )}
        </div>
      </div>
    );
  }

  // Success state
  if (submitSuccess) {
    return (
      <div className="space-y-6">
        {brandingSection}
        <div className="flex flex-col items-center justify-center h-64 text-center">
          <h2 className="text-2xl font-bold text-green-600 mb-4">
            {t("modules.pages.customerForm.formSubmitted.title")}
          </h2>
          <p className="text-gray-600">
            {t("modules.pages.customerForm.formSubmitted.message")}
          </p>
          {mode === "dialog" && (
            <p className="text-sm text-gray-500 mt-2">
              {t("modules.pages.customerForm.formSubmitted.autoClose")}
            </p>
          )}
        </div>
      </div>
    );
  }

  const formData = tokenValidation;
  const expiryDate = new Date(formData?.expired_at ?? Date.now());
  const expiryTime = format(expiryDate, "HH:mm:ss");

  // Create options for selects
  const countryOptions =
    countries?.map((country) => ({
      value: country.id.toString(),
      label: country.name,
    })) || [];

  const cityOptions =
    cities?.map((city) => ({
      value: city.id.toString(),
      label: city.name,
    })) || [];

  const stateOptions =
    states?.map((state) => ({
      value: state.id.toString(),
      label: state.name,
    })) || [];

  const genderOptions = [
    { label: t("common.fields.gender.male"), value: "male" },
    { label: t("common.fields.gender.female"), value: "female" },
  ];

  // Show preview notification for agents
  const showPreviewBanner = isPreviewMode && isUserAuthenticated;

  const formContent = (
    <div className="space-y-6">
      {/* NomadRem branding */}
      {brandingSection}

      {/* Preview banner for agents */}
      {showPreviewBanner && (
        <div className="text-center bg-yellow-50 border border-yellow-200 p-4 rounded-lg">
          <p className="text-sm text-yellow-800 font-medium">
            {t("modules.pages.customerForm.previewMode")}
          </p>
        </div>
      )}

      {/* Error message */}
      {submitError && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
          <p className="text-sm text-red-700">{submitError}</p>
        </div>
      )}

      <Form {...form}>
        <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-2 gap-y-5">
            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.firstName.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="firstName"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.firstName.placeholder")}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.lastName.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="lastName"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.lastName.placeholder")}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.email.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.email.placeholder")}
                        type="email"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.phone.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="phoneNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <PhoneInput
                        placeholder={t("common.fields.phone.placeholder")}
                        countryOptions={countryPhoneOptions}
                        selectedCountry={form.watch("countryPhoneCode")}
                        phoneNumber={field.value}
                        onCountryChange={(countryCode: string) =>
                          form.setValue("countryPhoneCode", countryCode)
                        }
                        onPhoneChange={field.onChange}
                        error={
                          form.formState.errors.countryPhoneCode?.message ||
                          form.formState.errors.phoneNumber?.message
                        }
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.streetName.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="streetName"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.streetName.placeholder")}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.houseNumber.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="houseNumber"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.houseNumber.placeholder")}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.postalCode.label")}
              </Label>
              <FormField
                control={form.control}
                name="postalCode"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t("common.fields.postalCode.placeholder")}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.extraAddressDetails.label")}
              </Label>
              <FormField
                control={form.control}
                name="extraAddressDetails"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <Input
                        placeholder={t(
                          "common.fields.extraAddressDetails.placeholder"
                        )}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <SearchableSelect
              label={`${t("common.fields.country.label")}*`}
              placeholder={t("common.fields.country.placeholder")}
              options={countryOptions}
              value={form.watch("countryId")?.toString() || ""}
              onChange={(value) => {
                const countryId = parseInt(value.toString());
                form.setValue("countryId", countryId);
                handleCountryChange(countryId);
              }}
              error={form.formState.errors.countryId?.message}
              loading={false}
              required
            />

            <SearchableSelect
              label={`${t("common.fields.city.label")}*`}
              placeholder={t("common.fields.city.placeholder")}
              options={cityOptions}
              value={form.watch("cityId")?.toString() || ""}
              onChange={(value) =>
                form.setValue("cityId", parseInt(value.toString()))
              }
              error={form.formState.errors.cityId?.message}
              loading={false}
              disabled={!selectedCountryId}
              required
            />

            <SearchableSelect
              label={t("common.fields.state.label")}
              placeholder={t("common.fields.state.placeholder")}
              options={stateOptions}
              value={form.watch("stateId")?.toString() || ""}
              onChange={(value) =>
                form.setValue("stateId", parseInt(value.toString()))
              }
              error={form.formState.errors.stateId?.message}
              loading={false}
              disabled={!selectedCountryId}
            />

            <div className="flex flex-col gap-1">
              <Label className="text-[14px]">
                {t("common.fields.dob.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="dateOfBirth"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <DatePicker
                        value={field.value}
                        onChange={field.onChange}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="md:col-span-2 flex flex-col gap-2">
              <Label>
                {t("common.fields.gender.label")}
                <span className="text-red-500">*</span>
              </Label>
              <FormField
                control={form.control}
                name="gender"
                render={({ field }) => (
                  <FormItem>
                    <FormControl>
                      <div className="flex items-center gap-2">
                        {genderOptions?.map((genderOption) => (
                          <button
                            key={genderOption.value}
                            type="button"
                            className={cn(
                              "w-full flex items-center border gap-1 rounded-lg px-4 py-3 text-[14px] text-left transition",
                              "border-gray-200 bg-white"
                            )}
                            onClick={() => {
                              setSelectedGender(genderOption.value);
                              field.onChange(genderOption.value);
                            }}
                          >
                            {selectedGender === genderOption.value ? (
                              <CheckedIcon />
                            ) : (
                              <UncheckedIcon />
                            )}
                            {t(`common.fields.gender.${genderOption.value}`)}
                          </button>
                        ))}
                      </div>
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          </div>

          <Button
            type="submit"
            className="w-full bg-teal-600 hover:bg-teal-700 text-white py-3 rounded-lg font-medium"
            disabled={isSubmitting || submitMutation.isPending || isPreviewMode}
          >
            {isPreviewMode
              ? t("modules.pages.customerForm.previewModeSubmitDisabled")
              : isSubmitting || submitMutation.isPending
              ? t("common.actions.submitting")
              : t("modules.pages.customerForm.signUp")}
          </Button>
        </form>
      </Form>
    </div>
  );

  if (mode === "dialog") {
    return formContent;
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-2xl mx-auto bg-white rounded-lg shadow-lg p-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900">
            {t("modules.pages.customerForm.createAccount")}
          </h1>
          <p className="text-gray-600 mt-2">
            {t("modules.pages.customerForm.usingLinkOf")}{" "}
            <span className="font-semibold">
              {`${formData?.first_name ?? ""} ${
                formData?.last_name ?? ""
              }`.trim() || t("modules.pages.customerForm.unnamed")}
            </span>
            . {t("modules.pages.customerForm.linkExpireAt")}{" "}
            <span className="font-semibold">{expiryTime}</span>
          </p>
        </div>
        {formContent}
      </div>
    </div>
  );
};

export default CustomerForm;
